### ISSUE TITLE
Waiting until successfully deployed

### ISSUE THREAD

**Issue by andyslack** [zulhfreelancer/aws-codepipeline-action#3]
Hi Zulhilmi,

Love this action, well done for creating it.

I wonder if there is a way to validate a successful deployment before proceeding? 

My use case is that I deploy via Code Pipeline into a Elastic Beanstalk, then I run my unit testing against the beanstalk.

The problem is, it takes 1-2 mins to deploy, so I could add a 'wait' into the code but it would be better to get some kind of success message back from the code pipeline endpoint before the action continues?

Thoughts?

**Comment by solarmosaic-kflorence** [comment]
I have the same need. It is possible, as this action supports it for Codebuild: https://github.com/aws-actions/aws-codebuild-run-build

**Comment by kflorence** [comment]
@andyslack you can try https://github.com/solarmosaic/aws-codepipeline-execute
